### ISSUE TITLE
Windows install issue

### ISSUE THREAD

**Issue by SoftologyPro** [sony/genwarp#6]
When the `pip install -r requirements.txt` step runs it gives the following error

```
Cloning into 'genwarp'...
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (50/50), done.
Receiving objects: 100% (68/68), 1.39 MiB | 4.85 MiB/s, done.d 0 (from 0)

Resolving deltas: 100% (24/24), done.
Filtering content: 100% (2/2), 225.24 KiB | 179.00 KiB/s, done.
Cloning into 'extern/ZoeDepth'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (77/77), done.
Receiving objects: 100% (111/111), 4.09 MiB | 7.46 MiB/s, done. 6 (from 1)

Resolving deltas: 100% (39/39), done.
Requirement already satisfied: pip in d:\blah\genwarp\venv\lib\site-packages (23.0.1)
Collecting pip
  Downloading pip-24.2-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 5.3 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-24.2
Collecting git+https://github.com/pesser/splatting (from -r requirements.txt (line 10))
  Cloning https://github.com/pesser/splatting to c:\users\jason\appdata\local\temp\pip-req-build-7ujpv57_
  Running command git clone --filter=blob:none --quiet https://github.com/pesser/splatting 'C:\Users\Jason\AppData\Local\Temp\pip-req-build-7ujpv57_'
  Resolved https://github.com/pesser/splatting to commit 1427d7c4204282d117403b35698d489e0324287f
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "D:\blah\genwarp\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\blah\genwarp\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\blah\genwarp\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Jason\AppData\Local\Temp\pip-build-env-0o9orey4\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Jason\AppData\Local\Temp\pip-build-env-0o9orey4\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\Jason\AppData\Local\Temp\pip-build-env-0o9orey4\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Jason\AppData\Local\Temp\pip-build-env-0o9orey4\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

`D:\blah\` is the temp directory I am using for testing.
To make it easier to reproduce the issue, create a new empty directory and save the following as bug.bat inside that directory.  It creates a new clean virtual env for the Python packages and installs them into that venv.

```
@echo off
if exist genwarp\. rd /S /Q genwarp
git clone https://github.com/sony/genwarp
cd genwarp
git clone https://github.com/isl-org/ZoeDepth.git extern/ZoeDepth
python -m venv venv
call venv\scripts\activate.bat
python -m pip install --upgrade pip
pip install -r requirements.txt
```

Then open a command prompt, change into your temp empty folder and run bug.bat.  That wil get the same error as above.

**Comment by kaz-sony** [comment]
Hi @SoftologyPro , It seems the error is caused while installing 'splatting'. Could you also check their repo to find your issue? The error message says that it couldn't find 'torch'. So you may want to install torch before splatting.
As stated in the [README](https://github.com/sony/genwarp?tab=readme-ov-file#environment), we tested this repo only on Linux machines and recommend to use Docker to set up a virtual environment. Please check it also.

**Comment by SoftologyPro** [comment]
Torch was installed.  Confirmed by manually running all the requirements.txt installs.  pip list after the error also shows torch is installed.  splatting repo has no issues enabled to report the problem.  So no go for Windows for now (outside Docker).

**Comment by kaz-sony** [comment]
We are sorry that we couldn't support native Windows environments. Hope it works with Docker in your environment.

**Comment by zsc000722** [comment]
I met the same issue while install splatting on the Linux, could you please tell me how did you fix the problem finally?
